export const INTERVIEW_TYPES = {
    TECHNICAL: 'Technical',
    HR: 'HR',
    BEHAVIORAL: 'Behavioral'
};


export const ACTION_TYPES = {
    ADD_INTERVIEW: 'ADD_INTERVIEW',
    UPDATE_INTERVIEW: 'UPDATE_INTERVIEW',
    DELETE_INTERVIEW: 'DELETE_INTERVIEW',
    SET_FILTER: 'SET_FILTER',
    SET_NOTIFICATION: 'SET_NOTIFICATION'
};